### PR TITLE
Add Waters product statement

### PR DESCRIPTION
**Pull request by StefanTIB**
Add product statement for family of Waters informatics solutions

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [x ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [x ] Status: please select a value from the status table at the top
  - [ x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [x ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [x ] Please mind the sorting

### CODE REVIEW

**Review by tschmidtb51 — COMMENTED** [review]
@StefanTIB Thank you for your contribution. I would suggest to unfold the statement a little bit more to be able to make statements about "Affected" and "Not Affected" products.

**Comment by StefanTIB** [comment]
I do not have the overview per product available. 
Only the link to overview of all waters products.

**Comment by tschmidtb51** [comment]
> I do not have the overview per product available. Only the link to overview of all waters products.

Please extract the information from the link you provided or link (in accordance with the products) to the more specific pages which are linked on that page.

**Comment by StefanTIB** [comment]
That is too much work for me. I do not have time to sort this all out.

**Pull request closed without merging**
