### PR TITLE
Added Keeper SSO to software list

### PR DESCRIPTION
**Pull request by arjans1990**

### CODE REVIEW

**Comment by FF9680E59F9B** [comment]
It's unclear to me exactly what product of Keeper is vulnerable and how you have determined it. Could you please elaborate on this?

**Comment by arjans1990** [comment]
I have updated the product name. We are using this product and therefore received an email urging us to upgrade. 
image
Unfortunately, the release notes on their website does not provide sufficient information https://docs.keeper.io/release-notes/on-prem-components/sso-connect/sso-connect-version-16.0.2

**Comment by count0x00** [comment]
Hi Arjans1990, Can you provide a link to release notes telling the status of log4j on Keeper?

**Comment by arjans1990** [comment]
@count0x00 no. The release notes (also linked in my pervious comment) are not detailed at all: https://docs.keeper.io/release-notes/on-prem-components/sso-connect/sso-connect-version-16.0.2 I will try to find the initial email from them which indicates tu upgrade to this version.

**Comment by FF9680E59F9B** [comment]
Thanks. I'll add a link to the screenshot to the list.

**Pull request merged**
