### PR TITLE
Added note from Schneider Electric about APC software

### PR DESCRIPTION
**Pull request by ipbgeek**
Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - Status: please select a value from the status table at the top
  - Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - Please mind the sorting
  - Please put vendor/product name in PR title (instead of "Update README.md")

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@ipbgeek That looks weird as you state that it is vulnerable and at the same time under investigation... Moreover, I could not find a hint in the Schneider Electric document where they mention the PowerChute Business Edition. Could you please explain that?

**Comment by ipbgeek** [comment]
It was originally marked vulnerable before I checked the master list. If you check the software packages (I have and use PowerChute for Business here at work) it comes bundled with  log4j api and core version 2.14.1 on the latest version which is 10.0.4

The company statement just means they're checking everything and don't have specifics. For the PowerChute vulnerability claim I have it, so I'll upload a picture to show what I mean.

PowerChuteForBusiness10 0 4 Log4J
PowerChuteForBusiness10 0 4 Properties

**Comment by tschmidtb51** [comment]
Thank you for the information. However, I think your PR should the reference the image you provided...

Just a quick question: Did you check (as in actually test) that it is vulnerable? I know some vendors which remove unused classes before shipping or don't call certain functions. This is also related to the [VEX](https://ntia.gov/files/ntia/publications/vex_one-page_summary.pdf) discussion...

**Comment by ipbgeek** [comment]
I've not manually tested it no. I was going purely on version numbers of the vulnerable editions. Feel free to wait for the official response from Schneider (I am as well). I was just trying to inform as of their broad statement about their products since there wasn't any info up yet.

**Comment by maertsen** [comment]
We'll await a vendor statement. Thanks for the time both of you have spent tracing this. We look forward to a future PR, i'll close this one to simplify bookkeeping.

**Pull request closed without merging**
