### PR TITLE
Added more updates for Red Hat products

### PR DESCRIPTION
**Pull request by paderijk**
Updated/added RedHat entries as listed on their CVE page.

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [x] Status: please select a value from the status table at the top
  - [x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [x] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [x] Please mind the sorting

### CODE REVIEW

**Review by grayum — CHANGES_REQUESTED** [review]
Thank you for your pull request. However I see that you didn't put the version number in a separate column. Could please change that for all submitted changes and resubmit?

**Comment by paderijk** [comment]
I've added the Red Hat Security Advisory IDs (RHSA-2021:XXXX) just like with my [previous PR 541](https://github.com/NCSC-NL/log4shell/pull/541) which got approved earlier.

So in thought that it was sufficient.

**Comment by paderijk** [comment]
@grayum I added the version numbers (also from the products which I updated earlier), hope all went right with the commit.

Please review.

**Comment by grayum** [comment]
hi @paderijk Having the version in a separate column gives a better overview but I see what you mean with #541. Thanks for the extra work on your end for this PR.

**Pull request merged**
