### PR TITLE
Added Planon Software

### PR DESCRIPTION
**Pull request by PlanonSecurityTeam**

### CODE REVIEW

**Review by maertsen — CHANGES_REQUESTED** [review]
Hi @PlanonSecurityTeam. Thanks for contributing information about this software. Unfortunately, we have no way of verifying the connection between Planon the company and @PlanonSecurityTeam the github user. Can you link a statement on your website or social media?

**Comment by PlanonSecurityTeam** [comment]
Hi maertsen,

Only a link for our customers behind login; https://my.planonsoftware.com/uk/news/log4j-impact-on-planon

**Review by maertsen — CHANGES_REQUESTED** [review]
Thanks! Can you save that screenshot in the vendor-statements directory? I'll merge your contribution.

**Comment by PlanonSecurityTeam** [comment]
Hi @maertsen, Added a screenshot.

**Review by maertsen — APPROVED** [review]

**Pull request merged**
