### PR TITLE
Add BCT

### PR DESCRIPTION
**Pull request by bct-lvb**
Added BCT products (Corsa, Liber, BCE, IDT, e-Invoice, iGEN) to Readme.md.

### CODE REVIEW

**Review by tschmidtb51 — COMMENTED** [review]
Please add version strings where applicable in the correct field (and make sure they match the status fields).

**Comment by bct-lvb** [comment]
I have corrected the Version column for the BCT products for which a fix is available (Liber and e-Invoice).

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
Thank you for your contribution.

Please sort the product names according to alphabet.

You also have unrelated changes in here which affect Schneider Electric. Therefore, please update your PR.

**Comment by tschmidtb51** [comment]
@bct-lvb: Thank you for the contribution.

Unfortunately, you still have unrelated changes here which affect the Schneider Electric entries. There are 2 ways to resolve them:
1. Open a new PR based on the current version. OR
2. Merge the current version into your existing PR.

Please let me know if you need additional advise.

**Comment by bct-lvb** [comment]
I've tried to merge the current version from the main branch into this PR, as you suggested, so all contents are the same now, with the addition of BCT products. Have I done this right?

**Comment by bct-lvb** [comment]
By the way, I don't even know how the Schneider Electric entries got affected in the first place. I've never touched them. I've used GitHub's functionality to edit the Readme.md file and only added the BCT entries, but it appears those changes got already in the first commit somehow.

**Comment by tschmidtb51** [comment]
> I've tried to merge the current version from the main branch into this PR, as you suggested, so all contents are the same now, with the addition of BCT products. Have I done this right?

Unfortunately, no. But that is my fault - I didn't explain what I meant by "Merge the current version into your existing PR." I was thinking of [syncing the fork/branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

As it might be quite complex to clean this up via the web-UI: Do you mind if we close this PR and you create a new one? The safest way to do that would be to [fork the repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and edit the file in the fork and then [provide a new Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

Feel free to mention me (@tschmidtb51) in the PR so that I get a notification to look at it.

**Comment by bct-lvb** [comment]
My apologies for the inconvenience. Let's indeed close this PR and start a new one. Who would've thought that using GitHub's web-UI functionality would be so hard to use? ;) I'll just do it the old-fashioned way with my trusted IDE for the new PR. Thanks for your help so far and I'll tag you in the new PR.

**Pull request closed without merging**
