### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tolimar**
Add status for IBM Power Hardware Management Consoles

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - Status: please select a value from the status table at the top
  - Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - Please mind the sorting
  - Please put vendor/product name in PR title (instead of "Update README.md")

### CODE REVIEW

**Comment by count0x00** [comment]
Hi Tolimar, I see you propose to change:

[source](https://launchpad.support.sap.com/#/notes/3130698)
into:
<https://launchpad.support.sap.com/#/notes/0003130499>

And:
| BMC Software  | zDetect  | | Not vuln |  |[source](https://community.bmc.com/s/news/aA33n000000TSUdCAO/bmc-security-advisory-for-cve202144228-log4shell-vulnerability) |
into:
| BMC Software  | zDetect  | Not vuln |  | |[source](https://community.bmc.com/s/news/aA33n000000TSUdCAO/bmc-security-advisory-for-cve202144228-log4shell-vulnerability) |

This doesn't seem to me to be the propper format. Can you motivate this?

**Comment by tolimar** [comment]
> Hi Tolimar, I see you propose to change:
> 
> [source](https://launchpad.support.sap.com/#/notes/3130698) into: https://launchpad.support.sap.com/#/notes/0003130499
> 
> And: | BMC Software | zDetect | | Not vuln | |[source](https://community.bmc.com/s/news/aA33n000000TSUdCAO/bmc-security-advisory-for-cve202144228-log4shell-vulnerability) | into: | BMC Software | zDetect | Not vuln | | |[source](https://community.bmc.com/s/news/aA33n000000TSUdCAO/bmc-security-advisory-for-cve202144228-log4shell-vulnerability) |
> 
> This doesn't seem to me to be the propper format. Can you motivate this?

Sorry, something went wrong.  I actually wanted to add lines for the IBM Power Hardware Managment controllers instead of editing existing entries.  I'll see if I can find out, how to clean my patch.

**Review by maertsen — CHANGES_REQUESTED** [review]
thanks @tolimar, we'll be awaiting your updated PR.

**Comment by count0x00** [comment]
Hi Tolimar, Are you still planning on fixing your entry?

**Pull request closed without merging**
