### PR TITLE
Add Fujifilm to software list

### PR DESCRIPTION
**Pull request by alkajazz**
from advisory sent by vendor

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [x] Status: please select a value from the status table at the top
  - [x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [x] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [x] Please mind the sorting

### CODE REVIEW

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
hi @alkajazz , thanks for contributing to the software list. Can you have a look at my remarks? Some changes are necessary before we can merge.

Please add a source. If Fujifilm doesn't have one publicly available, you could add a redacted statement to the adjacent folder vendor-statements.

**Comment by tschmidtb51** [comment]
Please also fix the following errors:
```
	 +|Fujifilm|Synapse 3D|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Synapse CV|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Synapse EIS|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Synapse Mobility|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Synapse PACS|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln|If the Oracle utility, SQL Developer, has been installed on a Synapse server, it will result in a positive finding. This utility is not required by the Synapse line of products and should be uninstalled out of an abundance of caution.|Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Synapse VNA|<6.3|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
	 +|Fujifilm|Vidistar|ALL|Not Vuln|Not Vuln|Not Vuln|Not Vuln||Advisory sent directly to customers.|
 		 ['Entry contains incorrect status value. Please check again.']
```
The correct status value would probably be `Not vuln`.

**Comment by ShaikhTaha** [comment]
Can you define it a little more please?

**Comment by tschmidtb51** [comment]
> Can you define it a little more please?

Sorry about the delayed reply. We are still unsure what you would like us to "define more"?

**Pull request closed without merging**
