### PR TITLE
Added link to Schneider Electric Security Bulletin

### PR DESCRIPTION
**Pull request by The-M-Peror**
Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - Status: please select a value from the status table at the top
  - Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - Please mind the sorting

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@The-M-Peror How is that related to the Schneider statement?

**Comment by The-M-Peror** [comment]
> @The-M-Peror How is that related to the Schneider statement?

Sorry if I didn't understand the goal correctly. I noticed that there was no link (yet) to a statement from Schneider Electric about APC Powerchute being vulnerable or not. Found such a statement where they mention investigating and how they will report progress. Thought that would be a useful addition.

**Comment by tschmidtb51** [comment]
Well, I guess we should add as much information as we have. However, I think referencing the Schneider Electric statement here might to more harm then good: The line says that APC PowerChute Business Edition is affected but the statement does not support that. It just says that Schneider Electric is investigating (or did I miss something here?).

As the status is not supported by the link I would suggest to not add the link at this stage.

@The-M-Peror: Does that make sense?

**Comment by The-M-Peror** [comment]
Hm, that makes sense. Will make a mental note to recheck if they add or update a statement with something more substantial.

**Pull request closed without merging**
