### PR TITLE
Add INIT GmbH

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Review by maertsen — CHANGES_REQUESTED** [review]
hi @skinkie, thanks  for reaching out!

We have no way to easily verify the connection between your github user and the organisation (INIT GmbH) your statement appears to be coming from. If the statement originates from an e-mail, can you attach a screenshot? Make sure to redact all personal data.
Please use a filename which includes the company name.

**Comment by skinkie** [comment]
Do you want me to put it in vendors or here?

image

**Comment by maertsen** [comment]
In vendors please. Don't forget to update the link. Thanks!

**Comment by skinkie** [comment]
Would you prefer https://archive.newsletter2go.com/?n2g=wq37zux3-w7nrbmnl-19ru instead?

**Comment by maertsen** [comment]
please rename the image to include the vendor name and we're done.

**Comment by maertsen** [comment]
Your contribution contained unrelated whitespace changes; but I've merged those too, because they looked OK. Thanks!

**Comment by skinkie** [comment]
@maertsen sorry for the extra whitespace stuff...

**Pull request merged**
