### PR TITLE
Add Soliton Systems

### PR DESCRIPTION
**Pull request by DFFspace**
Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - Status: please select a value from the status table at the top
  - Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - Please mind the sorting
  - Please put vendor/product name in PR title (instead of "Update README.md")

### CODE REVIEW

**Comment by FF9680E59F9B** [comment]
Thanks for your contribution. The source (https://blog.solitonsystems.com/news/update-on-log4j-vulnerability) shows that MailZen products have been updated or that an update is made available, but your pull request has the status "Not vuln" for all products. A product for which a patch has been supplied should have the "Fix" status.

**Comment by DFFspace** [comment]
I have updated it to Fix, do I have also to add separated rows for their products or is this fine?

**Comment by FF9680E59F9B** [comment]
I don't think adding a row for each product is necessary, but I would suggest putting something like this in the right format:
MailZen Management Portal - On-Premise - (v2.36.2, v2.37.3, v2.38.2) - Fix
MailZen Management - Cloud Service - Fix
MailZen Push Server - Fix
Other products - Not vuln

**Comment by FF9680E59F9B** [comment]
Thanks!

**Pull request merged**
