### PR TITLE
Update Dell

### PR DESCRIPTION
**Pull request by DFFspace**

### CODE REVIEW

**Review by sannemaasakkers — CHANGES_REQUESTED** [review]
Could you please split the name + version number in the right columns for SCG and add the right version number of Data Domain OS? Thank you for the detailed change!

**Comment by DFFspace** [comment]
Currently redoing their whole list of 244 items, almost done!

**Review by sannemaasakkers — CHANGES_REQUESTED** [review]
Thanks for this detailed contribution! Could you please change 'suit' to 'suite' for Wyse Windows Embedded Suite? Thank you! :)

**Comment by DFFspace** [comment]
Fixed that typo

**Comment by grayum** [comment]
Thanks for the effort @DFFspace. We've added new columns to add other relevant CVE's. Please fetch, update accordingly and issue a new PR. Thank you.

**Comment by DFFspace** [comment]
Updated them! Glad I made myself a Python script to quickly output the table markdown format for items

**Pull request merged**
